/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package be.gvdenbro.kilt

import be.gvdenbro.kilt.git.GitDescribeTask
import org.gradle.api.Project
import org.gradle.api.Plugin

class KiltPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'be.gvdenbro.kilt'")
            }
        }

        project.tasks.register("gitDescribe", GitDescribeTask::class.java) {
            it.group = "build"
            it.description = "Prints out the result of git describe"
        }
    }
}
