/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package be.gvdenbro.kilt

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'be.gvdenbro.kilt.greeting' plugin.
 */
class KiltPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("be.gvdenbro.kilt.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
